CREATE TABLE `historico_ocupacao_completo` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `data_referencia` DATE NOT NULL,
    `num_enf` INT NULL,
    `leito` INT NULL,
    `nome_enfermaria` VARCHAR(100) NULL,
    `status_leito` VARCHAR(50) NULL,
    `aih_paciente` VARCHAR(50) NULL,
    `cns_paciente` VARCHAR(50) NULL,
    `nome_paciente` VARCHAR(255) NULL,
    `sexo` CHAR(1) NULL,
    `data_nasc` DATE NULL,
    `idade` INT NULL,
    `data_internacao` DATETIME NULL,
    `data_internacao_leito` DATETIME NULL,
    `suspeita_covid` VARCHAR(20) NULL,
    `pos_covid` VARCHAR(20) NULL,
    `motivo_impedimento` VARCHAR(150) NULL,
    `data_impedimento` DATETIME NULL,
    `data_sol_reserva` DATETIME NULL,
    `previsao_intern_reserva` DATETIME NULL,
    `acompanhamento_data_hora` DATETIME NULL,
    `prontuario` VARCHAR(50) NULL,
    `cid_10` VARCHAR(50) NULL,
    `codigo_ser` VARCHAR(50) NULL,
    `perfil` VARCHAR(100) NULL,
    `bomba_infusora` VARCHAR(20) NULL,
    `suporte_cirurgico` VARCHAR(20) NULL,
    `suporte_alimentar` VARCHAR(50) NULL,
    `modo_ventilatorio` VARCHAR(100) NULL,
    `observacao` TEXT NULL,
    `cronico` VARCHAR(20) NULL,
    `longa_permanencia` VARCHAR(20) NULL,
    `situacao_motivo_permanencia` VARCHAR(255) NULL,
    `gestante` VARCHAR(20) NULL,
    `inducao_parto` VARCHAR(20) NULL,
    `arbovirose` VARCHAR(20) NULL,
    `viabilidade_dialise_peritoneal` VARCHAR(20) NULL,
    `infeccao_ativa_antibiotico` VARCHAR(20) NULL,
    `historico_cirurgias_abdominais` VARCHAR(20) NULL,
    `doenca_neoplasica_avancada` VARCHAR(20) NULL,
    `hernia_inguinal_reparar` VARCHAR(20) NULL,
    `condicoes_alta_dialise` VARCHAR(20) NULL,
    `inserido_no_trs` VARCHAR(20) NULL,
    `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    INDEX `idx_data_referencia` (`data_referencia`),
    INDEX `idx_status_leito` (`status_leito`),
    INDEX `idx_nome_paciente` (`nome_paciente`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;